[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.config/nvim/rc/plugins/denite.rc.vim'
hook_add = '''
  nnoremap <silent> fh
        \ :<C-u>Denite file_rec<CR>
  nnoremap <silent> fb
        \ :<C-u>Denite file_mru<CR>
  nnoremap <silent> ff
        \ :<C-u>Denite command command_history<CR>
  nnoremap <silent> ft :<C-u>Denite filetype<CR>
'''
